#!/bin/sh
export CUDA_HOME=/usr/local/cuda
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export LIBDEVICE_DIR=/usr/local/cuda/nvvm/libdevice
. /home/venv/bin/activate
python /home/ubuntu/scripts/fandmestimation.py